<a href="https://colab.research.google.com/github/Tahsin-20/CSE330-Numerical_Methods/blob/main/Lab%20Tasks/Lab%20Mid/Lab_Final_Solution_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from numpy.polynomial import Polynomial
import numpy as np

## **Question-01**

In [ ]:
p=Polynomial([0,1])
f=0.5*(p+8)**2+3
print(f)
print(f.degree())
f_prime=f.deriv(1)
print(f_prime(4)*f(4))

35.0 + 8.0·x + 0.5·x²
2
900.0


## **Question-02**

In [ ]:
x=[0, 1, 2, 3]
y=[5, 7, 9, 11]
node=len(x)
mat=np.zeros((node, node))
for i in range (node):
  for j in range (node):
    mat[i][j]=x[i]**(2*j)
print(mat)

[[  1.   0.   0.   0.]
 [  1.   1.   1.   1.]
 [  1.   4.  16.  64.]
 [  1.   9.  81. 729.]]


## **Question-03**

In [ ]:
x_data=[1, 3, 5]
y_data=[2, 12, 30]

def l(k, x, x_data):
  l_k=1
  for i in range (len(x_data)):
    if i!=k:
      l_k*=(x_data[k]-x_data[i])/(x_data[k]-x)
  return l_k

lagrange_bases=[]
for i in range (len(x_data)):
  lagrange_bases.append(l(i,7,x_data))
print(lagrange_bases)

p=0
for i in range (len(lagrange_bases)):
  p+=lagrange_bases[i]*y_data[i]
print(p)

[0.2222222222222222, -0.25, 2.0]
57.44444444444444


## **Question-04**

In [ ]:
g=Polynomial([8, 4, -5, 2])
x=2
h=0.5
g_prime=g.deriv(1)


def fwd_diff(x, h):
  return (g(x+h)-g(x))/h

while True:
  error=abs(g_prime(x)-fwd_diff(x,h))

  if error<0.0015:
    break
  h=h/4

print(h)
print(error)

0.0001220703125
0.0008545219898223877
